name: Build lsyncd static

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install deps
      run: |
        sudo apt update
        sudo apt install -y \
          build-essential autoconf automake libtool wget

    - name: Build Lua
      run: |
        wget https://www.lua.org/ftp/lua-5.3.6.tar.gz
        tar xzf lua-5.3.6.tar.gz
        cd lua-5.3.6
        make linux MYCFLAGS="-fPIC"

    - name: Build lsyncd
      run: |
        ./autogen.sh
        ./configure \
          LUA_CFLAGS="-I../lua-5.3.6/src" \
          LUA_LIBS="../lua-5.3.6/src/liblua.a -lm -ldl" \
          --enable-static \
          --disable-shared
        make

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: lsyncd
        path: src/lsyncd

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: src/lsyncd