name: Build lsyncd static

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            autoconf \
            automake \
            libtool \
            musl-tools \
            wget \
            git

      - name: Download lsyncd
        run: |
          git clone https://github.com/lsyncd/lsyncd.git

      - name: Build Lua
        run: |
          wget https://www.lua.org/ftp/lua-5.3.6.tar.gz
          tar xzf lua-5.3.6.tar.gz
          cd lua-5.3.6/src
          make CC=musl-gcc MYCFLAGS="-fPIC" liblua.a -j2

      - name: Build lsyncd
        run: |
          cd lsyncd
          autoreconf -fvi

          ./configure \
            CC=musl-gcc \
            CFLAGS="-O2 -static" \
            LUA_CFLAGS="-I../lua-5.3.6/src" \
            LUA_LIBS="../lua-5.3.6/src/liblua.a -lm -ldl"

          make -j2

      - name: Package
        run: |
          mkdir release
          cp lsyncd/src/lsyncd release/lsyncd-linux-amd64
          strip release/lsyncd-linux-amd64

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: lsyncd
          path: release/*